example
enumeration
	^ '(DW_TAG_enumeration_type)
    <1116>   DW_AT_byte_size   : 4
    <1117>   DW_AT_type        : <0x77>
    <111b>   DW_AT_decl_file   : 5
    <111c>   DW_AT_decl_line   : 259
    <111e>   DW_AT_sibling     : <0x1132>
 <2><1122>: Abbrev Number: 36 (DW_TAG_enumerator)
    <1123>   DW_AT_name        : (indexed string: 0xc32): UDTYPE_USERDATA
    <1125>   DW_AT_const_value : 0
 <2><1126>: Abbrev Number: 36 (DW_TAG_enumerator)
    <1127>   DW_AT_name        : (indexed string: 0x33): UDTYPE_IO_FILE
    <1128>   DW_AT_const_value : 1
 <2><1129>: Abbrev Number: 36 (DW_TAG_enumerator)
    <112a>   DW_AT_name        : (indexed string: 0x498): UDTYPE_FFI_CLIB
    <112c>   DW_AT_const_value : 2
 <2><112d>: Abbrev Number: 36 (DW_TAG_enumerator)
    <112e>   DW_AT_name        : (indexed string: 0x14a): UDTYPE__MAX
    <1130>   DW_AT_const_value : 3
'