example
struct
   ^ '(DW_TAG_structure_type)
    <45>   DW_AT_name        : (indexed string: 0xe8): __va_list_tag
    <47>   DW_AT_byte_size   : 24
    <48>   DW_AT_decl_file   : 1
    <49>   DW_AT_decl_line   : 0
    <4a>   DW_AT_sibling     : <0x77>
 <2><4e>: Abbrev Number: 8 (DW_TAG_member)
    <4f>   DW_AT_name        : (indexed string: 0xd52): gp_offset
    <51>   DW_AT_decl_file   : 1
    <52>   DW_AT_decl_line   : 0
    <53>   DW_AT_type        : <0x77>
    <57>   DW_AT_data_member_location: 0
 <2><58>: Abbrev Number: 8 (DW_TAG_member)
    <59>   DW_AT_name        : (indexed string: 0x789): fp_offset
    <5b>   DW_AT_decl_file   : 1
    <5c>   DW_AT_decl_line   : 0
    <5d>   DW_AT_type        : <0x77>
    <61>   DW_AT_data_member_location: 4
 <2><62>: Abbrev Number: 8 (DW_TAG_member)
    <63>   DW_AT_name        : (indexed string: 0xcd8): overflow_arg_area
    <65>   DW_AT_decl_file   : 1
    <66>   DW_AT_decl_line   : 0
    <67>   DW_AT_type        : <0x7c>
    <6b>   DW_AT_data_member_location: 8
 <2><6c>: Abbrev Number: 8 (DW_TAG_member)
    <6d>   DW_AT_name        : (indexed string: 0xcda): reg_save_area
    <6f>   DW_AT_decl_file   : 1
    <70>   DW_AT_decl_line   : 0
    <71>   DW_AT_type        : <0x7c>
    <75>   DW_AT_data_member_location: 16'